import Head from "next/head";

import Link from "next/link";

import styles from "../styles/Home.module.css";

export default function Home({ posts }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Next Pwa Tutorial</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="manifest" href="/manifest.json" />
      </Head>

      <h1>My Posts</h1>
      <div className={styles.grid}>
        {posts.map((post) => (
          <Link key={post.id} href={`/${post.id}`}>
            <a className={styles.card}>
              <h2>{post.title} &rarr;</h2>
              <p>{post.body}</p>
            </a>
          </Link>
        ))}
      </div>
    </div>
  );
}

export const getStaticProps = async () => {
  const res = await fetch("https://jsonplaceholder.typicode.com/posts");
  const data = await res.json();
  const posts = data.slice(0, 4);

  return {
    props: {
      posts,
    },
  };
};
